version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_db # имя БД
    ports:
      - '5444:5432'
    volumes:
      - D:/temywka_D/VS code_D/SQL_db/Ef_Mob_db:/var/lib/postgresql/data
      - ./internal/db/migrations:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
